from agents.base_agent import BaseAgent
import pandas as pd

class MonitorExplainLearnAgent(BaseAgent):
    def __init__(self):
        super().__init__(name="MonitorAgent")
        self.final_plan = None
        
        self.register_tool(self.get_metrics)
        self.register_tool(self.get_cuts_summary)
        
        self.set_system_instruction(
            """
            You are the Monitor, Explain, and Learn Agent.
            Your job is to review the final demand plan and provide a natural language report.
            1. Get metrics using 'get_metrics'.
            2. Check for any negotiated cuts using 'get_cuts_summary'.
            3. Write a concise report explaining the plan, any issues found, and recommendations for next time.
            """
        )

    def get_metrics(self) -> str:
        """Returns key metrics of the plan."""
        if self.final_plan is None: return "Error: Plan not loaded."
        
        total_volume = self.final_plan['Constrained_Plan'].sum()
        return f"Total Planned Volume: {total_volume:.2f}"

    def get_cuts_summary(self) -> str:
        """Returns a summary of any cuts made during negotiation."""
        if self.final_plan is None: return "Error: Plan not loaded."
        
        cuts = self.final_plan[self.final_plan['Negotiation_Log'] != ""]
        if len(cuts) == 0:
            return "No cuts were made. Capacity was sufficient."
            
        total_cut_volume = (self.final_plan['Plan'] - self.final_plan['Constrained_Plan']).sum()
        affected_skus = cuts['SKU'].unique()
        return f"Capacity constraints triggered {len(cuts)} cuts, totaling {total_cut_volume:.2f} units. Affected SKUs: {list(affected_skus)}"

    def run(self, final_plan: pd.DataFrame, prompt: str = None) -> dict:
        self.final_plan = final_plan
        
        prompt = "Please generate the final demand planning report."
        explanation = super().run(prompt)
        
        # In this PoC, we package the text explanation into the report dict
        return {
            'metrics': {'total_volume': self.final_plan['Constrained_Plan'].sum()},
            'explanations': [explanation],
            'learnings': ["(Generated by Gemini) See explanation above."]
        }

if __name__ == "__main__":
    pass
